Repository KSP-CKAN/KSP2-NetKAN, pull requests merged in 2023-12, with the labels that each got.

#115 Fix HideOrbits install
  NetKAN/HideOrbits.netkan
Labels: Fix install

#51 Add Unity Explorer
  NetKAN/UnityExplorer.netkan
Labels: Blocked on mod author, Mod request

#117 Freeze SuicideBurn
  NetKAN/SuicideBurn.frozen
Labels: Freeze

#122 Add Kesa dependency
  NetKAN/KESASolar.netkan
  NetKAN/Kesa.netkan
Labels: Fix relationships
